imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, node_modules/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.0
    tests:
        override:
            -
                command: "make test phpcs phpmd phpstan"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
